# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lmucassi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/06/06 15:16:59 by lmucassi          #+#    #+#              #
#    Updated: 2017/07/22 17:37:46 by lmucassi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC = ft_putchar.c\
	  ft_isalnum.c\
	  ft_isalpha.c\
	  ft_isdigit.c\
	  ft_isprint.c\
	  ft_strcmp.c\
	  ft_strncmp.c\
	  ft_strcpy.c\
	  ft_strncpy.c\
	  ft_strlen.c\
	  ft_strstr.c\
	  ft_tolower.c\
	  ft_toupper.c\
	  ft_strdup.c\
	  ft_strrchr.c\
	  ft_strchr.c\
	  ft_strnstr.c\
	  ft_strlcat.c\
	  ft_isascii.c\
	  ft_strncat.c\
	  ft_strcat.c\
	  ft_memcmp.c\
	  ft_memchr.c\
	  ft_memmove.c\
	  ft_memccpy.c\
	  ft_memcpy.c\
	  ft_bzero.c\
	  ft_memset.c\
	  ft_atoi.c\
	  ft_memalloc.c\
	  ft_memdel.c\
	  ft_striteri.c\
	  ft_strnew.c\
	  ft_strdel.c
	  
SRCO = ft_strlen.o\
	   ft_strcpy.o\
	   ft_strncpy.o\
	   ft_strstr.o\
	   ft_strcmp.o\
	   ft_strncmp.o\
	   ft_isalpha.o\
	   ft_isdigit.o\
	   ft_isalnum.o\
	   ft_isprint.o\
	   ft_toupper.o\
	   ft_tolower.o\
	   ft_putchar.o\
	   ft_strdup.o\
	   ft_strrchr.o\
	   ft_strchr.o\
	   ft_strnstr.o\
	   ft_strlcat.o\
	   ft_isascii.o\
	   ft_strncat.o\
	   ft_strcat.o\
	   ft_memcmp.o\
	   ft_memchr.o\
	   ft_memmove.o\
	   ft_memccpy.o\
	   ft_memcpy.o\
	   ft_bzero.o\
	   ft_memset.o\
	   ft_atoi.o\
	   ft_memalloc.o\
	   ft_memdel.o\
	   ft_striteri.o\
	   ft_strnew.o\
	   ft_strdel.o

CFLAGS = -Wall -Wextra -Werror

all: $(NAME)
	
$(NAME):
	gcc -c $(CFLAGS) $(SRC)
	ar rc $(NAME) $(SRCO)
	ranlib $(NAME)

clean:
	rm -f $(SRCO)

fclean: clean
	rm -f $(NAME)

re: fclean all
